import { v4 as uuidv4 } from "https://jspm.dev/uuid";

export const thoughtsData = [
    {
        userName: "@maso",
        displayName: "Maso",
        profilePic: "images/maso.webp",
        likes: 12,
        retweets: 3,
        tweetText: "I made this app. What do you think? Let me know in the comments!",
        isLiked: false,
        isRetweeted: false,
        showComments: false,
        comments: [
            {
                profilePic: "images/hater.webp",
                userName: "@hater45",
                commentText: "No one cares bro. But I love you",
            },
        ],
        uuid: uuidv4(),
        timestamp: "2h",
    },
    {
        userName: "@realdonaldtrump",
        displayName: "Donald J. Trump",
        profilePic: "images/donald.webp",
        likes: 45892,
        retweets: 12453,
        tweetText: "Mars is part of America actually. We will make the universe great again!",
        isLiked: false,
        isRetweeted: false,
        showComments: false,
        comments: [
            {
                profilePic: "images/french.webp",
                userName: "@frenchman9",
                commentText: "Trust me bro... I am a better president",
            },
            {
                profilePic: "images/romeo.webp",
                userName: "@romeo12",
                commentText: "Can you make me vice president?",
            },
        ],
        uuid: uuidv4(),
        timestamp: "4h",
    },
    {
        userName: "@elon",
        displayName: "Elon Musk",
        profilePic: "images/elon.webp",
        likes: 89234,
        retweets: 23891,
        tweetText: "Tomorrow I will start a new company that shoots rocks into space, trying to fight aliens. The future is now.",
        isLiked: false,
        isRetweeted: false,
        showComments: false,
        comments: [],
        uuid: uuidv4(),
        timestamp: "8h",
    },
    {
        userName: "@paveldurov",
        displayName: "Pavel Durov",
        profilePic: "images/pavel.webp",
        likes: 34521,
        retweets: 8923,
        tweetText: "I don't use my phone. Privacy is not a privilege, it's a right.",
        isLiked: false,
        isRetweeted: false,
        showComments: false,
        comments: [
            {
                profilePic: "images/goat.webp",
                userName: "@hunterUX",
                commentText: "Telegram is sooo good bro!",
            },
        ],
        uuid: uuidv4(),
        timestamp: "12h",
    },
    {
        userName: "@ronaldo",
        displayName: "Cristiano Ronaldo",
        profilePic: "images/ronaldo.webp",
        likes: 234567,
        retweets: 67891,
        tweetText: "You know who the real GOAT is. SIUUUUU!",
        isLiked: false,
        isRetweeted: false,
        showComments: false,
        comments: [],
        uuid: uuidv4(),
        timestamp: "1d",
    },
];
